#
# CPSC 323 Parser Project
# Author: YOUR NAME HERE
# Your task is to implement a parser using the default grammar 
# parser csv table generated by the Java program.
#

import csv


class Parser:
    """
    This class parses the token stream outputted from the lexical analyzer 
    into a parse tree or produces errors if the program is malformed.
    """
    def __init__(self, token_stream, parse_table_filename: str, grammar_rules_filename: str):
        """
        Class constructor takes the token stream output from the 
        lexical analyzer as input. Appends $ to the end of the stream.
        """
        # token_stream
        # ex: [ (token, type) , (token, type) ]
        self.token_stream = token_stream

        # Append the end of file symbol to the end.
        self.token_stream.append(("$", "$"))

        print(f"token stream: \n{self.token_stream}")

        # Create Stack
        self.stack = ['E']

        # push state 0 onto stack
        self.stack.append('0')

        # self.parser_table = self.__read_parse_table(parse_table_file)
        self.parser_table = self.__read_parse_table(parse_table_filename)
        print(f"PARSE TABLE: {self.parser_table}")

        # Create Grammar Rules
        self.grammar_rules = {}

        # set grammar rules dict
        self.grammar_rules = self.__read_grammar_rules(grammar_rules_filename)

    def __read_parse_table(self, parse_table_file: str):
        """
        Reads the parse table from a file.
        @param parse_table_file The file path for the parse table csv file.
        @return A dictionary/map (state, symbol) -> action/goto.
            dict format: {symbol: [instruction, instruction]}
        """
        # extracts the parse_table csv file
        with open(parse_table_file, "r") as file:
            file = csv.reader(file)

            temp_csv = list(file)

        # parses the csv into a dict object
        # ex: {symbol: [instruction, instruction]}
        parser_dict = self.__parse_to_dict(temp_csv)

        return parser_dict

    def __read_grammar_rules(self, grammar_rules_file: str):
        """
        Reads the grammar dict from a file
        :param grammar_rules_file: grammar dict filename
        :return: grammar dict:
            ex: {symbol: [instruction, instruction]}
        """
        # extracts the parse_table csv file
        with open(grammar_rules_file, "r") as file:
            file = csv.reader(file)

            temp_csv = list(file)

        # parses the grammar rules into a dict object
        # ex: {symbol: [instruction, instruction]}
        grammar_dict = self.__parse_to_dict(temp_csv)

        return grammar_dict

    def __parse_to_dict(self, csv_file: csv):
        """
        helper function for __read_parse_table
        parses a csv.reader object into a parse_dict

        :param csv_file: csv object pulled from parse_tale_file in __read_parse_table
        :return: a formatted parser dict
        """
        parser_dict = {}
        row_list = []

        # iterates through first row in parser table
        for row in csv_file:
            row_list = row

            # extracts csv header
            for item in row_list:
                parser_dict.update({item: []})

            # leaves after it grabs the csv header
            break

        # iterates through csv file and creates a dict that uses header as the keys
        for row in csv_file:
            i = 0

            while i < len(row):
                # FIXME this is not the optimal way of doing this
                if row[i] != row_list[i]:
                    parser_dict[row_list[i]].append(row[i])
                i += 1

        parser_dict[''].pop()
        parser_dict[''] = row_list

        return parser_dict

    def __check_parse_table(self, token: str, state: str):
        """

        :param state:
        :param token:
        :return:
        """
        # looks up result on parser table
        # FIXME brittle code
        # ToDo delete test code

        # reminder token = ( token, type )

        if type(token) is tuple:
            # because token is: ( token, type ) token[1] allows parser to search token type in parse table
            return self.parser_table[token[1]][int(state)]
        else:
            return self.parser_table[token][int(state)]



    def __has_next_token(self):
        """
        @return True if the token stream is not empty.
        """
        return len(self.token_stream) != 0

    def __get_next_token(self):
        """
        Fetches and consumes the next token in the input.
        @return tuple (token, type)
        """
        if self.__has_next_token():
            to_return = self.token_stream[0]
            self.token_stream.pop(0)
            return to_return
        return None

    # pseudo-stack functions

    def __stack_top(self):
        #FIXME -> complete documentation
        """
        pseudo top function for the self.stack
        list has all the rest of the functions needed for a stack
        :return: either the item at the top of stack or null if empty
        """
        if len(self.stack) > 0:
            return self.stack[len(self.stack)-1]
        else:
            return None

    def __stack_pop(self):
        #FIXME -> complete documentation
        """

        :return:
        """
        return self.stack.pop(len(self.stack)-1)

    def __stack_push(self, push_item):
        #FIXME -> complete documentation
        """

        :param push_item:
        :return:
        """
        self.stack.append(push_item)

    # reduction steps
    def __reduce_token(self, action: str, token: str):
        #FIXME -> complete documentation
        """

        :param action:
        :param token:
        :return:
        """
        pops = int(self.grammar_rules[action][2])


        #self.__stack_pop()
        #self.__stack_pop()

        while pops != 0:
            self.__stack_pop()
            pops -= 1

        non_terminal = self.grammar_rules[action][0]

        next_stack_item = self.__stack_top()

        self.__stack_push(non_terminal)


        result = self.__check_parse_table(non_terminal, next_stack_item)
        # parser_table[non_terminal][int(next_stack_item)]
        # self.__stack_push(non_terminal)

        self.__stack_push(result)


    # shift steps
    def __shift(self, action, token):
        # FIXME complete documentation
        """


        :param action:
        :param token:
        :return:
        """
        # push token
        self.stack.append(token)
        # push parsing_table_row
        new_action = action[1:]
        self.stack.append(new_action)

    def __check_accepting_state(self, token):
        #FIXME complete documentation
        """

        :param token:
        :return:
        """
        if token == "ACCT":
            return True
        else:
            return False

    def __parse_action(self, action, token):
        #FIXME -> complete documentation
        """

        :param token:
        :return:
        """
        # may not be needed
        success = 0

        if action == '' or token is None:
            success = 0
            raise "empty token"

        if action == "ACCT":
            return "ACCT: parsing_complete"

            # shift
        elif action[0] == 'S':
            success = 1
            self.__shift(action, token)

            # reduce
        elif action[0] == 'R':
            success = 1
            self.token_stream.insert(0, token)
            self.__reduce_token(action, token)

        elif isinstance(action, int):
            success = self.__check_accepting_state(action)
            if not success:
                raise "not accepted state. check code"
        else:
            success = 0
            raise "unknown error"

        return success

    def parse(self):
        #FIXME -> complete documentation
        """

        :return:
        """
        success = ("  ___  _____  _____ _____            _____ _   _ _____  _____  _____ _____ _____\n"
                   " / _ \\/  __ \\/  __ \\_   _|          /  ___| | | /  __ \\/  __ \\|  ___/  ___/  ___|\n"
                   "/ /_\\ \\ /  \\/| /  \\/ | |    ______  \\ `--.| | | | /  \\/| /  \\/| |__ \\ `--.\\ `--. \n"
                   "|  _  | |    | |     | |   |______|  `--. \\ | | | |    | |    |  __| `--. \\`--. \\\n"
                   "| | | | \\__/\\| \\__/\\ | |            /\\__/ / |_| | \\__/\\| \\__/\\| |___/\\__/ /\\__/ /\n"
                   "\\_| |_/\\____/ \\____/ \\_/            \\____/ \\___/ \\____/ \\____/\\____/\\____/\\____/ \n")
        start = ("----------------------------------------------------------------------------------\n"
                 "\t______ _____ _____ _____ _   _  ______  ___  ______  _____ _____\n"
                 "\t| ___ \\  ___|  __ \\_   _| \\ | | | ___ \\/ _ \\ | ___ \\/  ___|  ___|\n"
                 "\t| |_/ / |__ | |  \\/ | | |  \\| | | |_/ / /_\\ \\| |_/ /\\ `--.| |__ \n"
                 "\t| ___ \\  __|| | __  | | | . ` | |  __/|  _  ||    /  `--. \\  __| \n"
                 "\t| |_/ / |___| |_\\ \\_| |_| |\\  | | |   | | | || |\\ \\ /\\__/ / |___ \n"
                 "\t\\____/\\____/ \\____/\\___/\\_| \\_/ \\_|   \\_| |_/\\_| \\_|\\____/\\____/\n"
                 "----------------------------------------------------------------------------------")

        print(start)

        action_result = 1
        step = 1

        print(f"{'STEP' :<5} {'STACK' :<15} {'STREAM' :<11} {'Table Lookup' :<15}")
        while action_result != "ACCT: parsing_complete":

            print_stack = ''
            print_stream = ''

            for item in self.token_stream:
                print_stream += item[0]

            for item in self.stack:
                if type(item) == tuple:
                    print_stack += item[0]
                else:
                    print_stack += item

            working_token = self.__get_next_token()
            state = self.__stack_top()

            action = self.__check_parse_table(working_token, state)
            print(f"{step :<5} {print_stack :<15} {print_stream :<11} "
                  f"{'['+working_token[0]+','+state+']='+action:<15} ")

            action_result = self.__parse_action(action, working_token)

            if action_result == 0:
                raise "ERROR action_result = 0"
            if action_result == "ACCT: parsing_complete":
                print(f"{action_result} -> SUCCESS \n"
                      f"{success}")

            step += 1


if __name__ == "__main__":

    parser = Parser([], "parsing_table.csv", "grammar_table.csv")


