#
# CPSC 323 Parser Project
# Author: YOUR NAME HERE
# Your task is to implement a parser using the default grammar 
# parser csv table generated by the Java program.
#

import csv


class Parser:
    """
    This class parses the token stream outputted from the lexical analyzer 
    into a parse tree or produces errors if the program is malformed.
    """
    def __init__(self, token_stream, parse_table_filename: str, grammar_rules_filename: str):
        """
        Class constructor takes the token stream output from the 
        lexical analyzer as input. Appends $ to the end of the stream.
        """
        # token_stream is the stack
        self.token_stream = token_stream

        # Append the end of file symbol to the end.
        self.token_stream.append(("$", "$"))

        # Create Stack
        self.stack = []

        # push state 0 onto stack
        self.stack.append('0')

        # self.parser_table = self.__read_parse_table(parse_table_file)
        self.parser_table = self.__read_parse_table(parse_table_filename)

        # Create Grammar Rules
        self.grammar_rules = {}

        # set grammar rules dict
        self.grammar_rules = self.__read_grammar_rules(grammar_rules_filename)

    def __read_parse_table(self, parse_table_file: str) -> dict[str:list]:
        """
        Reads the parse table from a file.
        @param parse_table_file The file path for the parse table csv file.
        @return A dictionary/map (state, symbol) -> action/goto.
            dict format: {symbol: [instruction, instruction]}
        """
        # extracts the parse_table csv file
        with open(parse_table_file, "r") as file:
            file = csv.reader(file)

            temp_csv = list(file)

        # parses the csv into a dict object
        # ex: {symbol: [instruction, instruction]}
        parser_dict = self.__parse_to_dict(temp_csv)

        return parser_dict

    def __read_grammar_rules(self, grammar_rules_file: str) -> dict[str:list]:
        """
        Reads the grammar dict from a file
        :param grammar_rules_file: grammar dict filename
        :return: grammar dict:
            ex: {symbol: [instruction, instruction]}
        """
        # extracts the parse_table csv file
        with open(grammar_rules_file, "r") as file:
            file = csv.reader(file)

            temp_csv = list(file)

        # parses the grammar rules into a dict object
        # ex: {symbol: [instruction, instruction]}
        grammar_dict = self.__parse_to_dict(temp_csv)

        return grammar_dict

    def __parse_to_dict(self, csv_file: csv) -> dict[str:list]:
        """
        helper function for __read_parse_table
        parses a csv.reader object into a parse_dict

        :param csv_file: csv object pulled from parse_tale_file in __read_parse_table
        :return: a formatted parser dict
        """
        parser_dict = {}
        row_list = []

        # iterates through first row in parser table
        for row in csv_file:
            row_list = row

            # extracts csv header
            for item in row_list:
                parser_dict.update({item: []})

            # test code
            print(parser_dict)

            # leaves after it grabs the csv header
            break

        # iterates through csv file and creates a dict that uses header as the keys
        for row in csv_file:
            print(row)
            i = 0

            while i < len(row):
                # FIXME this is not the optimal way of doing this
                if row[i] != row_list[i]:
                    parser_dict[row_list[i]].append(row[i])
                i += 1

        parser_dict[''].pop()
        parser_dict[''] = row_list

        print(parser_dict)

        return parser_dict

    def __check_parse_table(self, state: str, token: str) -> str:

        # looks up result on parser table
        # FIXME brittle code
        return self.parser_table[state][self.parser_table[''].index(state)]


    def __has_next_token(self):
        """
        @return True if the token stream is not empty.
        """
        return len(self.token_stream) != 0

    def __get_next_token(self):
        """
        Fetches and consumes the next token in the input.
        @return tuple (token, type)
        """
        if self.__has_next_token():
            to_return = self.token_stream[0]
            self.token_stream.pop(0)
            return to_return
        return None

    def __top(self):
        """
        pseudo top function for the self.stack
        list has all the rest of the functions needed for a stack
        :return: either the item at the top of stack or null if empty
        """
        if len(self.stack) > 0:
            return self.stack[len(self.stack)-1]
        else:
            return None

    def __reduce_token(self, token):
        raise NotImplementedError()
        pass

    def __shift(self, action, token):
        # FIXME complete documentation
        """
        
        
        :param action: 
        :param token: 
        :return: 
        """
        # push token
        self.stack.append(token)
        # push parsing_table_row
        self.stack.append(action[1])


    def __check_accepting_state(self, token):
        raise NotImplementedError()
        pass

    def __parse_action(self, action, token):
        """

        :param token:
        :return:
        """
        # may not be needed
        success = 0

        if token == '' or token is None:
            success = 0
            raise "empty token"

        if token == "ACCT":
            return "ACCT: parsing_complete"

        elif token[0] == 'S':
            success = 1
            self.__shift(action, token)
        elif token[0] == 'R':
            success = 1
            self.__reduce_token(token)
        elif isinstance(token, int):
            success = 1
            self.__check_accepting_state(token)
        else:
            success = 0
            raise "unknown error"

        return success

    def parse(self):

        raise NotImplementedError()

        action_result = 1

        while action_result != "ACCT":

            next_token = self.__get_next_token()

            state = self.__top()

            lookup_result = self.__check_parse_table(state, next_token)

            action = self.parser_table[next_token]

            action_result = self.__parse_action(action, next_token)

            if action_result == 0:
                raise "ERROR action_result = 0"






if __name__ == "__main__":

    parser = Parser([], "parsing_table.csv", "grammar_table.csv")


