#
# CPSC 323 Parser Project
# Author: YOUR NAME HERE
# Your task is to implement a parser using the default grammar 
# parser csv table generated by the Java program.
#

import csv


class Parser:
    """
    This class parses the token stream outputted from the lexical analyzer 
    into a parse tree or produces errors if the program is malformed.
    """
    def __init__(self, token_stream, parse_table_file):
        """
        Class constructor takes the token stream output from the 
        lexical analyzer as input. Appends $ to the end of the stream.
        """
        self.token_stream = token_stream
        # self.parser_table = self.__read_parse_table(parse_table_file)
        self.parser_table = self.read_parse_table(parse_table_file)
        # Append the end of file symbol to the end.
        self.token_stream.append(("$", "$"))

    def __read_parse_table(self, parse_table_file):
        """
        Reads the parse table from a file.
        @param parse_table_file The file path for the parse table csv file.
        @return A dictionary/map (state, symbol) -> action/goto.
        """
        with open(parse_table_file, "r") as file:
            file = csv.reader(file)

            parser_dict = {}
            row_list = []

            for row in file:
                row_list = row

                for item in row_list:
                    parser_dict.update({item: []})
                break

            for row in file:
                print(row)
                i = 0
                while i < len(row):
                    parser_dict[row_list[i]].append(row[i])
                    i += 1

            parser_dict.pop('')
            
            return parser_dict

    def __csv_parse_to_dict(self, csv_file):
        pass

        raise NotImplementedError()

    def __has_next_token(self):
        """
        @return True if the token stream is not empty.
        """
        return len(self.token_stream) != 0

    def __get_next_token(self):
        """
        Fetches and consumes the next token in the input.
        @return tuple (token, type)
        """
        if self.__has_next_token():
            to_return = self.token_stream[0]
            self.token_stream.pop(0)
            return to_return
        return None

    def parse(self):
        print(self.__get_next_token())
        raise NotImplementedError()


if __name__ == "__main__":

    parser = Parser([], "parsing_table.csv")


